name: Tweepy Bot Workflow

on:
  schedule:
    - cron: "0 6 * * *"  # 毎日6時に実行
  workflow_dispatch:

jobs:
  run-tweepy-bot:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.SERVICE_ACCOUNT_CLIENT_ID }}
      SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}
      SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
      SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY_ID }}
      SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.SERVICE_ACCOUNT_PROJECT_ID }}
      SERVICE_ACCOUNT_TYPE: ${{ secrets.SERVICE_ACCOUNT_TYPE }}
      SERVICE_ACCOUNT_CLIENT_X509_CERT_URL: ${{ secrets.SERVICE_ACCOUNT_CLIENT_X509_CERT_URL }}
      SERVICE_ACCOUNT_AUTH_URI: ${{ secrets.SERVICE_ACCOUNT_AUTH_URI }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          if [ -f /usr/bin/chromium ]; then
            sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome || true
          else
            sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome || true
          fi

      - name: Create Google Credentials JSON file
        run: |
          echo "{" > credentials.json
          echo "\"type\": \"${{ secrets.SERVICE_ACCOUNT_TYPE }}\"," >> credentials.json
          echo "\"project_id\": \"${{ secrets.SERVICE_ACCOUNT_PROJECT_ID }}\"," >> credentials.json
          echo "\"private_key_id\": \"${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY_ID }}\"," >> credentials.json
          echo -n "\"private_key\": \"" >> credentials.json
          echo "${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}" | sed 's/\\n/\n/g' >> credentials.json
          echo "\"," >> credentials.json
          echo "\"client_email\": \"${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}\"," >> credentials.json
          echo "\"client_id\": \"${{ secrets.SERVICE_ACCOUNT_CLIENT_ID }}\"," >> credentials.json
          echo "\"auth_uri\": \"${{ secrets.SERVICE_ACCOUNT_AUTH_URI }}\"," >> credentials.json
          echo "\"token_uri\": \"https://oauth2.googleapis.com/token\"," >> credentials.json
          echo "\"auth_provider_x509_cert_url\": \"${{ secrets.SERVICE_ACCOUNT_CLIENT_X509_CERT_URL }}\"," >> credentials.json
          echo "\"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}\"" >> credentials.json
          echo "}" >> credentials.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tweepy Bot (scraping)
        run: |
          python tweepybot_scraping_tuge.py

      - name: Run Tweepy Bot (main)
        run: |
          python tweepybot.py
