name: Tweepy Bot Workflow

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-tweepy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy JSON
        run: |
          cat <<EOF > credentials.json
{
  "dummy": "dummy"
}
EOF
      - name: Finish
        run: echo "Done"
