name: Tweepy Bot Multi-Client

on:
  schedule:
    - cron: "30 23 * * *"    # 毎日 23:30 UTC → 翌日 08:30 JST
  workflow_dispatch:        # 手動トリガーも残す

jobs:
  run-bot:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - client: cl0001
            SPREADSHEET_URL:    ${{ secrets.CLIENT0001_SHEET_URL }}
            EVENT_URLS:         ${{ secrets.CLIENT0001_EVENT_URLS }}
            TW_BEARER_TOKEN:    ${{ secrets.CLIENT0001_TW_BEARER_TOKEN }}
            TW_CONSUMER_KEY:    ${{ secrets.CLIENT0001_TW_CONSUMER_KEY }}
            TW_CONSUMER_SECRET: ${{ secrets.CLIENT0001_TW_CONSUMER_SECRET }}
            TW_ACCESS_TOKEN:    ${{ secrets.CLIENT0001_TW_ACCESS_TOKEN }}
            TW_ACCESS_SECRET:   ${{ secrets.CLIENT0001_TW_ACCESS_SECRET }}
          - client: cl0002
            SPREADSHEET_URL:    ""
            EVENT_URLS:         ""
            TW_BEARER_TOKEN:    ""
            TW_CONSUMER_KEY:    ""
            TW_CONSUMER_SECRET: ""
            TW_ACCESS_TOKEN:    ""
            TW_ACCESS_SECRET:   ""
          - client: cl0003
            SPREADSHEET_URL:    ""
            EVENT_URLS:         ""
            TW_BEARER_TOKEN:    ""
            TW_CONSUMER_KEY:    ""
            TW_CONSUMER_SECRET: ""
            TW_ACCESS_TOKEN:    ""
            TW_ACCESS_SECRET:   ""

    env:
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      CLIENT:               ${{ matrix.client }}
      SPREADSHEET_URL:      ${{ matrix.SPREADSHEET_URL }}
      EVENT_URLS:           ${{ matrix.EVENT_URLS }}
      TW_BEARER_TOKEN:      ${{ matrix.TW_BEARER_TOKEN }}
      TW_CONSUMER_KEY:      ${{ matrix.TW_CONSUMER_KEY }}
      TW_CONSUMER_SECRET:   ${{ matrix.TW_CONSUMER_SECRET }}
      TW_ACCESS_TOKEN:      ${{ matrix.TW_ACCESS_TOKEN }}
      TW_ACCESS_SECRET:     ${{ matrix.TW_ACCESS_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write Google credentials
        run: echo "$SERVICE_ACCOUNT_JSON" > credentials.json

      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          if [ -f /usr/bin/chromium ]; then
            sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome || true
          else
            sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome || true
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Plugin Loader
        if: env.SPREADSHEET_URL != ''
        run: python plugin_loader.py
        continue-on-error: true

      - name: Run Tweepy Bot (main)
        if: env.SPREADSHEET_URL != ''
        run: python tweepybot.py
