name: Tweepy Bot Workflow

on:
  schedule:
    - cron: "0 6 * * *"  # 毎日6時に実行
  workflow_dispatch:      # 手動実行を有効にする

jobs:
  run-tweepy-bot:
    runs-on: ubuntu-latest

    env: 
      SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.SERVICE_ACCOUNT_CLIENT_ID }}
      SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}
      SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
      SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY_ID }}
      SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.SERVICE_ACCOUNT_PROJECT_ID }}
      SERVICE_ACCOUNT_TYPE: ${{ secrets.SERVICE_ACCOUNT_TYPE }}
      SERVICE_ACCOUNT_CLIENT_X509_CERT_URL: ${{ secrets.SERVICE_ACCOUNT_CLIENT_X509_CERT_URL }}
      SERVICE_ACCOUNT_AUTH_URI: ${{ secrets.SERVICE_ACCOUNT_AUTH_URI }}

    steps:
      - uses: actions/checkout@v2

      - name: Create Google Credentials JSON file
        # 実際に認証ファイルを作るならコマンドを追記
               run: |
          printf "%s" "${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}" > credentials.json "${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}" > credentials.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tweepy Bot (scraping)
        run: |
          python tweepybot_scraping_tuge.py

      - name: Run Tweepy Bot (main)
        run: |
          python tweepybot.py
