name: Tweepy Bot Workflow

on:
  schedule:
    - cron: "0 6 * * *"   # 毎日 06:00 UTC（JST 15:00）。JST 06:00 実行にしたい場合は 0 21 * * * に変更。
  workflow_dispatch:

jobs:
  run-tweepy-bot:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Service‑Account JSON をファイルに書き出し
      - name: Write credentials.json
        run: echo "$SERVICE_ACCOUNT_JSON" > credentials.json
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      # 3) Chromium + Chromedriver をインストール
      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          if [ -f /usr/bin/chromium ]; then
            sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome || true
          else
            sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome || true
          fi

      # 4) Python セットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 5) 依存ライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6) スクレイピング用スクリプトを実行
      - name: Run Tweepy Bot (scraping)
        run: python tweepybot_scraping_tuge.py

      # 7) 投稿用スクリプトを実行
      - name: Run Tweepy Bot (main)
        run: python tweepybot.py
