name: Run Tweepy Bot

on:
  schedule:
    workflow_dispatch:
    - cron: '20 3 * * *'  # 日本時間 12:10 (JST) に実行 (UTC 03:10)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tweepy Bot
      run: |
        python your_bot_script.py  # スクリプト名を適切に変更
