name: Minimal Workflow

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create test file using heredoc
        run: |
          cat <<EOF > test.txt
Hello World
EOF

      - name: Show file content
        run: cat test.txt
