name: Minimal Workflow

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_VAR: "test"
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World"
