name: Tweepy Bot Workflow

on:
  schedule:
    # 23:00 UTC（JST 8:00）実行。JST 15:00 にしたい場合は 0 6 * * * に変更
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-tweepy-bot:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリ取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Google 認証ファイル作成
      - name: Write credentials.json
        run: echo "$SERVICE_ACCOUNT_JSON" > credentials.json
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      # 3) Chromium & Chromedriver
      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          if [ -f /usr/bin/chromium ]; then
            sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome || true
          else
            sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome || true
          fi

      # 4) Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 5) 依存ライブラリ
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6) Twitter API キー
      - name: Write twitter_key.json
        run: |
          cat > twitter_key.json <<'EOF'
          {
            "BEARER_TOKEN": "${{ secrets.TW_BEARER_TOKEN }}",
            "CONSUMER_KEY": "${{ secrets.TW_CONSUMER_KEY }}",
            "CONSUMER_SECRET": "${{ secrets.TW_CONSUMER_SECRET }}",
            "ACCESS_TOKEN": "${{ secrets.TW_ACCESS_TOKEN }}",
            "ACCESS_SECRET": "${{ secrets.TW_ACCESS_SECRET }}"
          }
          EOF

      # 7) スクレイピング
      - name: Run Tweepy Bot (scraping)
        run: python tweepybot_scraping_tuge.py
        continue-on-error: true        # ← 失敗しても後続へ進む

      # 8) 投稿
      - name: Run Tweepy Bot (main)
        run: python tweepybot.py
