name: Minimal Workflow

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create test file
        run: |
          cat <<EOF > test.txt
Hello World
EOF
      - run: echo "File created"
