name: Tweepy Bot Workflow

on:
  schedule:
    - cron: "0 6 * * *"  # 毎日6時に実行
  workflow_dispatch:

jobs:
  run-tweepy-bot:
    runs-on: ubuntu-latest
    env:
      DUMMY_VAR: "dummy"
    steps:
      - run: echo "Bot minimal. DUMMY_VAR=$DUMMY_VAR"
