name: Tweepy Bot Workflow

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-tweepy-bot:
    runs-on: ubuntu-latest
    env:
      DUMMY_VAR: "dummy"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: echo "Bot minimal. DUMMY_VAR=$DUMMY_VAR"
