name: Minimal Workflow

on:
  schedule:
    - cron: "0 6 * * *"  # 毎日6時に実行
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_VAR: "test"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create test file using heredoc
        run: |
          cat <<EOF > test.txt
Hello World
This is a heredoc test.
EOF

      - name: Show file content
        run: cat test.txt

      - name: Create dummy JSON
        run: |
          cat <<EOF > credentials.json
{
  "type": "dummy",
  "project_id": "dummy",
  "private_key_id": "dummy",
  "private_key": "dummy"
}
EOF

      - name: Show JSON file
        run: cat credentials.json

      - run: echo "Hello World. TEST_VAR is $TEST_VAR"
