name: Minimal Workflow

on:
  schedule:
    - cron: "0 6 * * *"  # 毎日6時に実行
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_VAR: "test"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create test file using heredoc
        run: |
          cat <<EOF > test.txt
